# nginx.conf
# This configures Nginx to act as a Round-Robin Load Balancer
events { worker_connections 1024; }

http {
    # Define the group of backend servers (the cluster)
    upstream backend_cluster {
        server app-node-1:3000;
        server app-node-2:3000;
        server app-node-3:3000;
    }

    server {
        listen 80;

        # Route all incoming public traffic to our backend cluster
        location / {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}